#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
bspc monitor eDP1 -d 1 2
bspc monitor HDMI1 -d 3 4

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          13
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Pavucontrol state=floating
bspc rule -a kitty state=floating